{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a1cd207d-6342-416d-99c9-8db084fa1be4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Say something...\n",
      "Error connecting to Google Speech Recognition service: recognition connection failed: [Errno 11001] getaddrinfo failed\n",
      "Say something...\n",
      "Error connecting to Google Speech Recognition service: recognition connection failed: [Errno 11001] getaddrinfo failed\n",
      "Say something...\n",
      "1/1 [==============================] - 12s 12s/step\n",
      "Error connecting to Google Speech Recognition service: recognition connection failed: [Errno 11001] getaddrinfo failed\n",
      "Say something...\n",
      "Error connecting to Google Speech Recognition service: recognition connection failed: [Errno 11001] getaddrinfo failed\n",
      "Say something...\n",
      "Error connecting to Google Speech Recognition service: recognition connection failed: [Errno 11001] getaddrinfo failed\n",
      "Say something...\n",
      "Error connecting to Google Speech Recognition service: recognition connection failed: [Errno 11001] getaddrinfo failed\n",
      "Say something...\n",
      "Error connecting to Google Speech Recognition service: recognition connection failed: [Errno 11001] getaddrinfo failed\n",
      "Say something...\n"
     ]
    }
   ],
   "source": [
    "import tkinter as tk\n",
    "import cv2\n",
    "import numpy as np\n",
    "from keras.models import model_from_json\n",
    "from keras.preprocessing import image\n",
    "from PIL import Image, ImageTk\n",
    "import speech_recognition as sr\n",
    "import threading\n",
    "\n",
    "# Load the pre-trained model\n",
    "model = model_from_json(open(\"model_fer.json\", \"r\").read())\n",
    "model.load_weights('model_fer.h5')\n",
    "\n",
    "# Initialize the face cascade classifier\n",
    "face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')\n",
    "\n",
    "# Initialize the speech recognizer\n",
    "recognizer = sr.Recognizer()\n",
    "\n",
    "# Function to process video frames and detect emotions\n",
    "def detect_emotions():\n",
    "    ret, frame = cap.read()\n",
    "    if not ret:\n",
    "        return\n",
    "\n",
    "    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)\n",
    "    faces = face_cascade.detectMultiScale(gray, 1.3, 5)\n",
    "\n",
    "    for (x, y, w, h) in faces:\n",
    "        roi_gray = gray[y:y + h, x:x + w]\n",
    "        roi_gray = cv2.resize(roi_gray, (48, 48))\n",
    "        img_pixels = image.img_to_array(roi_gray)\n",
    "        img_pixels = np.expand_dims(img_pixels, axis=0)\n",
    "        img_pixels /= 255.0\n",
    "\n",
    "        predictions = model.predict(img_pixels)\n",
    "        max_index = np.argmax(predictions[0])\n",
    "        emotions = ['Angry', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']\n",
    "        predicted_emotion = emotions[max_index]\n",
    "\n",
    "        cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)\n",
    "        cv2.putText(frame, predicted_emotion, (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)\n",
    "\n",
    "    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "    img = Image.fromarray(frame)\n",
    "    imgtk = ImageTk.PhotoImage(image=img)\n",
    "    video_label.imgtk = imgtk\n",
    "    video_label.configure(image=imgtk)\n",
    "\n",
    "    video_label.after(10, detect_emotions)\n",
    "\n",
    "# Function to handle speech recognition\n",
    "def recognize_speech():\n",
    "    while True:\n",
    "        with sr.Microphone() as source:\n",
    "            print(\"Say something...\")\n",
    "            recognizer.adjust_for_ambient_noise(source)\n",
    "            audio = recognizer.listen(source)\n",
    "\n",
    "        try:\n",
    "            speech_text = recognizer.recognize_google(audio)\n",
    "            print(\"You said: \", speech_text)\n",
    "            # You can add further processing or actions based on the recognized speech here\n",
    "        except sr.UnknownValueError:\n",
    "            print(\"Sorry, I could not understand audio.\")\n",
    "        except sr.RequestError as e:\n",
    "            print(f\"Error connecting to Google Speech Recognition service: {e}\")\n",
    "\n",
    "# Function to close the application\n",
    "def close_application():\n",
    "    cap.release()\n",
    "    cv2.destroyAllWindows()\n",
    "    window.destroy()\n",
    "\n",
    "# Create the main window\n",
    "window = tk.Tk()\n",
    "window.title(\"Real-Time Emotion Detection\")\n",
    "window.geometry(\"800x600\")\n",
    "\n",
    "# Create a label to display the video stream\n",
    "video_label = tk.Label(window)\n",
    "video_label.pack()\n",
    "\n",
    "# Create a button to close the application\n",
    "close_button = tk.Button(window, text=\"Close\", command=close_application)\n",
    "close_button.pack()\n",
    "\n",
    "# Open the video capture\n",
    "cap = cv2.VideoCapture(0)\n",
    "\n",
    "# Start the emotion detection process in a separate thread\n",
    "emotion_thread = threading.Thread(target=detect_emotions)\n",
    "emotion_thread.daemon = True\n",
    "emotion_thread.start()\n",
    "\n",
    "# Start speech recognition process in a separate thread\n",
    "speech_thread = threading.Thread(target=recognize_speech)\n",
    "speech_thread.daemon = True\n",
    "speech_thread.start()\n",
    "\n",
    "# Run the Tkinter event loop\n",
    "window.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "62a4cceb-74d2-45de-a931-4d3eec21f126",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
